Fix not showing all possible offline migration targets
SUSE/smt pull request #136
Opened 2020-07-09 17:10 UTC by felixsch

When calculating the offline migration targets in SCC, explicit offline
targets as well as all online targets are used.

This behaviour was never introduced to SMT. Add the behaviour to
`lookupMigrationTargetsById` to match the behaviour from SCC.

2020-07-09 17:23 UTC, ikapelyukhin approved these changes
I obviously haven't tested this, but code-wise LGTM.

2020-07-09 17:25 UTC, ikapelyukhin requested changes
You've got to bump up the version in the Makefile though:

https://github.com/SUSE/smt/blob/b2182abe0a3598a05bc97cf5724e9c7ee6a16ec8/Makefile#L2

2020-07-09 18:06 UTC, felixsch commented
Haha thanks I was already wondering if I missed it. Thanks for noticing!

2020-07-09 21:51 UTC, ikapelyukhin approved these changes

2020-07-10 10:07 UTC, digitaltom approved these changes
Looks good to me too. 
Could we push to the devel project, update on our SMT cloud node and verify?

2020-07-10 12:38 UTC, lcaparroz approved these changes
LGTM :+1:

2020-07-14 08:36 UTC, merged